const SAY_HELLO = 'SAY_HELLO';
const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS';
const SUBSCRIBE_TO_CHAT = 'SUBSCRIBE_TO_CHAT';
const UNSUBSCRIBE_TO_CHAT = 'UNSUBSCRIBE_TO_CHAT';
const GET_CHAT = 'GET_CHAT';
const POST_NEW_MESSAGE = 'POST_NEW_MESSAGE';
const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM';
const REQUEST_TO_JOIN_CHAT_ROOM = 'REQUEST_TO_JOIN_CHAT_ROOM';
const ACCEPT_REQUEST_TO_JOIN_CHAT_ROOM = 'ACCEPT_REQUEST_TO_JOIN_CHAT_ROOM';
const DECLINE_REQUEST_TO_JOIN_CHAT_ROOM = 'DECLINE_REQUEST_TO_JOIN_CHAT_ROOM';
const GET_REQUESTS_TO_JOIN_CHAT_ROOM = 'GET_REQUESTS_TO_JOIN_CHAT_ROOM';

export {
  SAY_HELLO,
  GET_CHAT_ROOMS,
  SUBSCRIBE_TO_CHAT,
  UNSUBSCRIBE_TO_CHAT,
  GET_CHAT,
  POST_NEW_MESSAGE,
  CREATE_CHAT_ROOM,
  REQUEST_TO_JOIN_CHAT_ROOM,
  ACCEPT_REQUEST_TO_JOIN_CHAT_ROOM,
  DECLINE_REQUEST_TO_JOIN_CHAT_ROOM,
  GET_REQUESTS_TO_JOIN_CHAT_ROOM
};
