const ALL_CHAT_ROOMS = 'ALL_CHAT_ROOMS';
const ALL_CHAT = 'ALL_CHAT';
const UPDATE_CHAT = 'UPDATE_CHAT';
const NEW_REQUEST = 'NEW_REQUEST';
const NEW_ACCEPTED_REQUEST = 'NEW_ACCEPTED_REQUEST';
const NEW_DECLINED_REQUEST = 'NEW_DECLINED_REQUEST';
const ALL_REQUESTS_TO_JOIN_CHAT_ROOM = 'ALL_REQUESTS_TO_JOIN_CHAT_ROOM';

export {
  ALL_CHAT_ROOMS,
  ALL_CHAT,
  UPDATE_CHAT,
  NEW_REQUEST,
  NEW_ACCEPTED_REQUEST,
  NEW_DECLINED_REQUEST,
  ALL_REQUESTS_TO_JOIN_CHAT_ROOM
};
