package com.tozaicevas.chat.dto;

public interface WebSocketRequestType {
    String SAY_HELLO = "SAY_HELLO";
    String SUBSCRIBE_TO_CHAT = "SUBSCRIBE_TO_CHAT";
    String UNSUBSCRIBE_TO_CHAT = "UNSUBSCRIBE_TO_CHAT";
    String GET_CHAT = "GET_CHAT";
    String GET_CHAT_ROOMS = "GET_CHAT_ROOMS";
    String POST_NEW_MESSAGE = "POST_NEW_MESSAGE";
    String CREATE_CHAT_ROOM = "CREATE_CHAT_ROOM";
    String REQUEST_TO_JOIN_CHAT_ROOM = "REQUEST_TO_JOIN_CHAT_ROOM";
    String ACCEPT_REQUEST_TO_JOIN_CHAT_ROOM = "ACCEPT_REQUEST_TO_JOIN_CHAT_ROOM";
    String DECLINE_REQUEST_TO_JOIN_CHAT_ROOM = "DECLINE_REQUEST_TO_JOIN_CHAT_ROOM";
    String GET_REQUESTS_TO_JOIN_CHAT_ROOM = "GET_REQUESTS_TO_JOIN_CHAT_ROOM";
}

